---

apiVersion: v1
kind: Pod
metadata:
  name: pdnm-my-pod                     # this is the actual pod name and will be seen on "k get pods"
  namespace: ns-london-apps             # pod will be created in this specific namespace. in the "default" namespace if not defined
                                        # some blogs say hardcoding like this reduces flexibility when deploy our apps
  labels:				# pod has 3 labels
    pdlb-environment: production
    pdlb-app: my-nginx
    pdlb-version: apr23
    
spec:
  containers:
  - name: ctr-nginx                     # actual container name
    image: nginx:1.14.2                 # image name and version, will be picked up from our pre-defined registry 
    ports:
    - containerPort: 80

