---
# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/

apiVersion: v1
kind: Pod
metadata:
  name: mtnm-simple-pod
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: pods-simple-container

apiVersion: v1
kind: Pod
metadata:
  name: mtnm-simple-pod-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

