---

apiVersion: v1
kind: Service
metadata:
  name: my-svc02-nodeport
spec:
  selector:
    app: products
    department: sales
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

# if we describe the service - 
#spec:
#  clusterIP: 10.11.254.114
#  externalTrafficPolicy: Cluster
#  ports:
#  - nodePort: 32675
#    port: 80
#    protocol: TCP
#    targetPort: 8080

