---
# https://cloud.google.com/kubernetes-engine/docs/concepts/service

apiVersion: v1
kind: Service
metadata:
  name: my-cip-service
spec:
  selector:
    app: metrics
    department: sales
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

#NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)
#my-cip-service   ClusterIP   10.11.247.213   none          80/TCP
