---

apiVersion: v1
kind: Service
metadata:
  name: my-svc02-loadbalancer
spec:
  selector:
    app: trade-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  clusterIP: 10.0.171.239
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
